-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 19:27:16 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey` DEFAULT CHARACTER SET utf8 ;
USE `survey` ;

-- -----------------------------------------------------
-- Table `survey`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` DATETIME NULL,
  `role` INT NULL COMMENT '0-调查员 1-评审员 2-管理员 3-调查主管',
  `nick_name` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `syndic_id` BIGINT NULL,
  `company` VARCHAR(32) NULL,
  `address` VARCHAR(64) NULL,
  `id_card` VARCHAR(32) NULL,
  `mobile_number` VARCHAR(32) NULL,
  `telephone_number` VARCHAR(32) NULL,
  `status` INT NOT NULL DEFAULT 0 COMMENT '0-未分配 1-已分配',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `surveyor_id` BIGINT NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `create_time` DATETIME NULL,
  `check_time` DATETIME NULL,
  `comment` VARCHAR(128) NULL,
  `point` VARCHAR(64) NULL,
  `type` VARCHAR(32) NULL,
  `status` INT NULL DEFAULT 0 COMMENT ' 0-待调查 1-开始调查 2已调查待审核 3-审核中4-审核成功 5-审核失败',
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `commit_time` DATETIME NULL,
  `summary` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`sign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`sign` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `sign_latitude` DOUBLE NOT NULL,
  `sign_longitude` DOUBLE NOT NULL,
  `actual_latitude` DOUBLE NOT NULL,
  `actual_longitude` DOUBLE NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`conf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`conf` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL,
  `photo_type` VARCHAR(64) NULL,
  `template` VARCHAR(64) NULL,
  `content` TEXT NULL,
  `pixel` VARCHAR(45) NULL,
  `type` INT NULL COMMENT '0-类型 1-照片类型 2-模板',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`photo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL,
  `task_id` BIGINT NOT NULL,
  `photo_type` BIGINT NULL,
  `path` VARCHAR(64) NULL,
  `create_time` DATETIME NULL,
  `content_type` VARCHAR(64) NULL,
  `extension` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `task_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `template_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`audio` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `task_id` BIGINT NOT NULL,
  `path` VARCHAR(64) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `content_type` VARCHAR(64) NOT NULL,
  `type` INT NOT NULL DEFAULT 0 COMMENT '0-临时的 1-正式的',
  `sequence` INT NOT NULL,
  `extension` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO user (account, password, create_time, role, nick_name) VALUES ('admin', 'c33367701511b4f6020ec61ded352059', now(), 2, null);
