CREATE TABLE `user` (
  `user_id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `password` varchar(100) DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
CREATE TABLE `cover_zone` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nation` varchar(500) NOT NULL,
  `district` varchar(500) NOT NULL,
  `cdnid` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `t_order` (
  `ordersid` int(11) NOT NULL AUTO_INCREMENT COMMENT '流水号',
  `userid` int(11) DEFAULT NULL COMMENT '用户流水号',
  `storeid` int(11) DEFAULT NULL COMMENT '店铺流水号',
  `deliverid` int(11) DEFAULT NULL COMMENT '快递员ID',
  `orderid` varchar(30) DEFAULT '未填写' COMMENT '订单流水号',
  `shipNo` varchar(30) DEFAULT '未填写' COMMENT '物流单号',
  `ship_name` varchar(30) NOT NULL DEFAULT '' COMMENT '发货的具体快递方式',
  `store_address` varchar(255) DEFAULT '未填写' COMMENT '店铺地址',
  `store_phone` varchar(255) DEFAULT '未填写' COMMENT '店铺电话',
  `catchtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
  `sid` int(11) DEFAULT '0' COMMENT '用户收货地址ID',
  `total_amount` decimal(10,4) unsigned NOT NULL DEFAULT '0.0000' COMMENT '订单原该支付总金额，orderTotal会扣掉抵扣券等',
  `orderTotal` decimal(10,4) DEFAULT '0.0000' COMMENT '该订单总价格',
  `points_fare` decimal(10,4) DEFAULT '0.0000' COMMENT '使用积分抵掉的价格',
  `invoice` tinyint(2) DEFAULT '0' COMMENT '0-不开发票，1-开发票',
  `invoice_fare` decimal(10,4) DEFAULT '0.0000' COMMENT '发票费用',
  `osid` int(11) DEFAULT NULL COMMENT '订单状态流水号',
  `after_sale_status` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '售后订单处理状态。0-订单状态正常无售后申请；1-售后订单正在处理中；2-售后订单已关闭，处理已完成',
  `sendway` varchar(255) DEFAULT '未填写' COMMENT '配送方式',
  `smid` tinyint(5) unsigned NOT NULL DEFAULT '0' COMMENT '配送方式ID',
  `fare` decimal(10,4) DEFAULT '0.0000' COMMENT '运费',
  `remark` text COMMENT '订单备注',
  `sendtime` timestamp NULL DEFAULT NULL COMMENT '发货时间',
  `gettime` timestamp NULL DEFAULT NULL COMMENT '收货时间',
  `order_url` varchar(255) DEFAULT '未填写' COMMENT '订单二维码url',
  `rolesid` int(11) DEFAULT '1' COMMENT '角色流水号',
  `retailid` int(11) DEFAULT NULL COMMENT '分销商ID',
  `scid` int(11) DEFAULT NULL COMMENT '店铺客服流水号',
  `user_del` tinyint(4) unsigned DEFAULT '0' COMMENT '订单个人是否删除；0:正常,1:删除',
  `store_del` tinyint(4) unsigned DEFAULT '0' COMMENT '订单商家是否删除；0:正常,1:删除',
  `is_review` tinyint(4) unsigned DEFAULT '0' COMMENT '评论状态,0-未评论,1-已评论,2-已追评,3-已回复(针对卖家而言)',
  `last_time` timestamp NULL DEFAULT NULL COMMENT '最近修改时间',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '成功支付的时间',
  `add_version` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '添加时的版本号',
  `is_returngoods` tinyint(2) DEFAULT '1' COMMENT '该订单是否允许申请售后(1-可以申请售后，0-不可以申请售后)',
  `postpone_ship` int(2) DEFAULT '0' COMMENT '延期收货天数（每次操作在前一次上做加法运算）',
  `postpone_count_user` int(2) DEFAULT '0' COMMENT '买家延期收货操作的次数(最多一次)',
  `postpone_count_store` int(2) DEFAULT '0' COMMENT '卖家延期收货的次数(不限次数)',
  PRIMARY KEY (`ordersid`)
) ENGINE=InnoDB AUTO_INCREMENT=7409 DEFAULT CHARSET=utf8 COMMENT='订单表';
